[package]
name = "sicp"
version = "0.1.0"
authors = ["julio <jcrinconc+phone@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "sicp"
path = "sicp.rs"
